#!/usr/local/bin/python3
"""
transform_title
Transform text to title case.
"""

__author__ = "José Muñiz"
__version__ = 1
__license__ = "MIT"
__script__ = "transform_title"

import sys
import subprocess


if __name__ == "__main__":
    text = subprocess.run(['pbpaste'], encoding='utf-8', capture_output=True)
    sys.stdout.write(f'{text.stdout.title()}')
